name: vivatranslate_mateus
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  audioplayers: ^1.1.0
  responsive_framework: ^0.2.0
  objectbox: ^1.7.0
  objectbox_flutter_libs: any
  intl: any
  path_provider: ^2.0.11
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  record: ^4.4.4
  record_windows: ^0.7.1
  record_macos: ^0.2.2
  permission_handler: ^10.2.0
  permission_handler_windows: ^0.1.2
  flutter_launcher_icons: ^0.11.0
  starflut: ^0.9.5
  flython: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any


flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/.keys/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
